In [ ]:
import numpy as np

In [ ]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0)
y = y/100

In [ ]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))    #Sigmoid Function

In [ ]:
def derivatives_sigmoid(x):
    return x * (1 - x)           #Derivative of Sigmoid Function

In [ ]:
epoch=6                         #Variable initialization
lr=0.1

In [ ]:
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

In [ ]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
  #Forward Propogation
  hinp1=np.dot(X,wh)
  hinp=hinp1 + bh
  hlayer_act = sigmoid(hinp)
  outinp1=np.dot(hlayer_act,wout)
  outinp= outinp1+bout
  output = sigmoid(outinp)
  #Backpropagation
  EO = y-output
  outgrad = derivatives_sigmoid(output)
  d_output = EO * outgrad
  EH = d_output.dot(wout.T)
  hiddengrad = derivatives_sigmoid(hlayer_act)
  d_hiddenlayer = EH * hiddengrad
  wout += hlayer_act.T.dot(d_output) *lr
  wh += X.T.dot(d_hiddenlayer) *lr
  print ("-----------Epoch-", i+1, "Starts----------")
  print("Input: \n" + str(X))
  print("Actual Output: \n" + str(y))
  print("Predicted Output: \n" ,output)
  print ("-----------Epoch-", i+1, "Ends----------\n")
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

-----------Epoch- 1 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.74961401]
 [0.73615699]
 [0.74959937]]
-----------Epoch- 1 Ends----------

-----------Epoch- 2 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.75277938]
 [0.73908818]
 [0.75277608]]
-----------Epoch- 2 Ends----------

-----------Epoch- 3 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.75582701]
 [0.74191393]
 [0.75583451]]
-----------Epoch- 3 Ends----------

-----------Epoch- 4 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.7587631 ]
 [0.74463971]
 [0.758